# Generated by Django 3.0.4 on 2020-11-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200428_2252'),
        ('erp', '0002_auto_20201113_1820'),
    ]

    operations = [
    ]
