# Generated by Django 3.0.4 on 2020-11-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_merge_20201117_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_update',
        ),
    ]
